// Code generated by aocgen; DO NOT EDIT.
package aoc

import (
	"aocgen/internal/year2024"
)

func RegisterYears() {
	Register(2024, map[int]Puzzle{1: year2024.Day01{},
		2: year2024.Day02{},
		3: year2024.Day03{},
		4: year2024.Day04{},
		5: year2024.Day05{},
		6: year2024.Day06{},
		7: year2024.Day07{},
	})
}
